import { StyleSheet } from 'react-native';

// Unified Design System - Universal Stylesheet for the entire app
export const universalStyles = StyleSheet.create({
  // ===== DESIGN SYSTEM TOKENS =====
  // Colors
  colors: {
    primary: '#4A90E2',        // Main brand blue
    primaryLight: '#E8F4FD',   // Light blue background
    secondary: '#4CAF50',      // Success green
    accent: '#FF6B35',         // Orange accent
    background: '#F8F9FA',     // Main background
    surface: '#FFFFFF',        // Card/surface background
    text: {
      primary: '#2C3E50',      // Main text
      secondary: '#7F8C8D',    // Secondary text
      light: '#FFFFFF',        // Light text on dark backgrounds
    },
    border: '#E1E8ED',         // Border color
    error: '#E74C3C',          // Error red
    success: '#27AE60',        // Success green
    warning: '#F39C12',        // Warning orange
  },

  // Spacing
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },

  // Border Radius
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    round: 50,
  },

  // Typography
  typography: {
    h1: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#2C3E50',
    },
    h2: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#2C3E50',
    },
    h3: {
      fontSize: 20,
      fontWeight: '600',
      color: '#2C3E50',
    },
    body: {
      fontSize: 16,
      color: '#2C3E50',
    },
    bodySmall: {
      fontSize: 14,
      color: '#7F8C8D',
    },
    button: {
      fontSize: 16,
      fontWeight: '600',
      color: '#FFFFFF',
    },
  },

  // ===== COMMON STYLES =====
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  scrollContainer: {
    flexGrow: 1,
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 24,
    textAlign: 'center',
    width: '100%',
    color: '#2C3E50',
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: '#2C3E50',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#2C3E50',
  },
  button: {
    backgroundColor: '#4A90E2',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingVertical: 8,
  },
  backButtonText: {
    fontSize: 16,
    marginLeft: 8,
    color: '#4A90E2',
    fontWeight: '500',
  },

  // ===== HOME SCREEN STYLES =====
  homeContainer: {
    flexGrow: 1,
    paddingTop: 80,
    paddingHorizontal: 24,
    backgroundColor: '#F8F9FA',
  },
  topContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  planButtonTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 56,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#E8F4FD',
    borderRadius: 12,
    width: '48%',
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  settingsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 56,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#E8F4FD',
    borderRadius: 12,
    width: '48%',
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  settingsLabel: {
    fontSize: 16,
    color: '#4A90E2',
    marginRight: 8,
    fontWeight: '500',
  },
  dimensionList: {
    justifyContent: 'center',
    marginTop: 24,
  },
  dimensionRow: {
    justifyContent: 'space-evenly',
    marginBottom: 24,
  },
  dimensionItem: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 120,
    height: 120,
    borderRadius: 60,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dimensionText: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '600',
  },
  badge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#2C3E50',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  noGoalsText: {
    textAlign: 'center',
    marginTop: 100,
    fontSize: 18,
    color: '#7F8C8D',
  },
  planButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
  },
  planButtonText: {
    fontSize: 16,
    marginLeft: 12,
    color: '#4A90E2',
    fontWeight: '500',
  },
  topButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  suggestedContainer: {
    marginTop: 32,
    padding: 20,
    backgroundColor: '#E8F4FD',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  suggestedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  suggestedHeaderToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 0,
  },
  suggestedHeaderText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  suggestedGoalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
  },

  // ===== GOAL SELECTION SCREEN STYLES =====
  goalSelectionContainer: {
    flex: 1,
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  goalSelectionPicker: {
    height: 56,
    width: '100%',
    marginBottom: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  goalSelectionAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 32,
    padding: 16,
    backgroundColor: '#E8F4FD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  goalSelectionAddButtonText: {
    fontSize: 18,
    marginLeft: 16,
    color: '#4A90E2',
    fontWeight: '600',
  },
  goalSelectionHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 24,
    color: '#2C3E50',
  },
  goalSelectionGoalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  goalSelectionGoalText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  goalSelectionRecurrenceContainer: {
    marginTop: 24,
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  goalSelectionRecurrenceOptions: {
    marginTop: 16,
  },

  // ===== GOAL SETTING SCREEN STYLES =====
  goalSettingContainer: {
    flex: 1,
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  goalSettingPicker: {
    height: 56,
    width: '100%',
    marginBottom: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  goalSettingInput: {
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    width: '100%',
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#2C3E50',
  },
  goalSettingQuantifiableToggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  goalSettingTargetInputContainer: {
    marginBottom: 20,
  },
  goalSettingTargetInput: {
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 12,
    padding: 16,
    width: '100%',
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#2C3E50',
  },
  goalSettingAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 32,
    padding: 16,
    backgroundColor: '#E8F4FD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  goalSettingAddButtonText: {
    fontSize: 18,
    marginLeft: 16,
    color: '#4A90E2',
    fontWeight: '600',
  },
  goalSettingDimensionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  goalSettingDimensionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  goalSettingGoalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  goalSettingSelectColorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    backgroundColor: '#4A90E2',
    borderRadius: 12,
    marginBottom: 16,
  },
  goalSettingSelectColorText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 12,
    fontWeight: '600',
  },

  // ===== DIMENSION GOALS SCREEN STYLES =====
  dimensionGoalsContainer: {
    flex: 1,
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  dimensionGoalsHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  dimensionGoalsHeaderText: {
    fontSize: 24,
    fontWeight: 'bold',
    marginLeft: 16,
    color: '#2C3E50',
  },
  dimensionGoalsGoalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dimensionGoalsGoalText: {
    fontSize: 16,
    color: '#FFFFFF',
    flex: 1,
    marginRight: 12,
    fontWeight: '500',
  },
  dimensionGoalsCompletedText: {
    textDecorationLine: 'line-through',
    color: '#BDC3C7',
  },
  dimensionGoalsCounterText: {
    fontSize: 18,
    color: '#2C3E50',
    marginVertical: 12,
    fontWeight: '600',
  },
  dimensionGoalsNoGoalsText: {
    textAlign: 'center',
    marginTop: 60,
    fontSize: 18,
    color: '#7F8C8D',
  },
  dimensionGoalsModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  dimensionGoalsModalContent: {
    backgroundColor: '#FFFFFF',
    padding: 24,
    borderRadius: 16,
    width: '85%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  dimensionGoalsModalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#2C3E50',
  },
  dimensionGoalsCounterButton: {
    padding: 16,
    backgroundColor: '#4A90E2',
    borderRadius: 12,
    marginVertical: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  dimensionGoalsCounterButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  dimensionGoalsCloseButton: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#4A90E2',
    marginTop: 24,
    minWidth: 100,
    alignItems: 'center',
  },
  dimensionGoalsCloseButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  dimensionGoalsTextInput: {
    height: 120,
    borderColor: '#E1E8ED',
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    width: '100%',
    marginBottom: 20,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#2C3E50',
  },

  // ===== HABIT TRACKING SCREEN STYLES =====
  habitTrackingContainer: {
    flex: 1,
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  habitTrackingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  habitTrackingHeaderText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  habitTrackingNoHabitsText: {
    textAlign: 'center',
    fontSize: 18,
    color: '#7F8C8D',
    marginTop: 40,
  },
  habitTrackingHabitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  habitTrackingHabitName: {
    flex: 1,
    fontSize: 18,
    marginLeft: 16,
    color: '#2C3E50',
    fontWeight: '500',
  },
  habitTrackingCounterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  habitTrackingCounterInput: {
    width: 60,
    height: 48,
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 12,
    textAlign: 'center',
    marginHorizontal: 12,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#2C3E50',
  },
  habitTrackingNewHabitContainer: {
    marginTop: 24,
    backgroundColor: '#E8F4FD',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  habitTrackingNewHabitHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  habitTrackingNewHabitHeaderText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  habitTrackingAddButton: {
    backgroundColor: '#4A90E2',
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
    alignItems: 'center',
  },
  habitTrackingAddButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  habitTrackingSummaryButton: {
    fontSize: 16,
    color: '#4A90E2',
    fontWeight: '600',
  },
  habitTrackingHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  habitTrackingSummaryButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#E8F4FD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  habitTrackingSummaryButtonText: {
    fontSize: 14,
    color: '#4A90E2',
    fontWeight: '600',
    marginLeft: 8,
  },
  habitTrackingHabitDetails: {
    flex: 1,
    marginLeft: 16,
  },
  habitTrackingProgressBarContainer: {
    width: '100%',
    height: 8,
    backgroundColor: '#E1E8ED',
    borderRadius: 4,
    marginTop: 8,
    overflow: 'hidden',
  },
  habitTrackingProgressBarFill: {
    height: '100%',
    backgroundColor: '#4A90E2',
    borderRadius: 4,
  },

  // ===== HABIT SUMMARY SCREEN STYLES =====
  habitSummaryContainer: {
    flexGrow: 1,
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  habitSummaryLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#2C3E50',
  },
  habitSummaryDateSelector: {
    flexDirection: 'row',
    marginBottom: 24,
  },
  habitSummaryGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  habitSummaryDayBox: {
    width: '13%',
    height: 60,
    margin: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  habitSummaryDayText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  habitSummaryCountText: {
    fontSize: 12,
    color: '#7F8C8D',
  },
  habitSummaryAverageText: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 24,
    textAlign: 'center',
    color: '#2C3E50',
  },
  habitSummaryBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    padding: 8,
  },
  habitSummaryBackText: {
    fontSize: 16,
    color: '#4A90E2',
    marginLeft: 8,
    fontWeight: '500',
  },

  // ===== ROUTINE TRACKING SCREEN STYLES =====
  routineTrackingContainer: {
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  routineTrackingEmptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingVertical: 60,
  },
  routineTrackingEmptyText: {
    fontSize: 18,
    marginBottom: 24,
    color: '#7F8C8D',
  },
  routineTrackingAddButton: {
    backgroundColor: '#4CAF50',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routineTrackingAddButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  routineTrackingRoutineContainer: {
    padding: 20,
    borderRadius: 16,
    marginVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routineTrackingRoutineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  routineTrackingRoutineEmoji: {
    fontSize: 40,
  },
  routineTrackingRoutineName: {
    fontSize: 22,
    fontWeight: 'bold',
    marginVertical: 12,
    color: '#FFFFFF',
  },
  routineTrackingRoutineDuration: {
    fontSize: 16,
    color: '#FFFFFF',
    opacity: 0.9,
  },
  routineTrackingProgressBar: {
    height: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    marginTop: 16,
    opacity: 0.3,
  },
  routineTrackingHeaderContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  routineTrackingTitleText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2C3E50',
  },

  // ===== ROUTINE EDITOR SCREEN STYLES =====
  routineEditorContainer: {
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  routineEditorLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 12,
    color: '#2C3E50',
  },
  routineEditorInput: {
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#2C3E50',
  },
  routineEditorColorPreview: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    borderRadius: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  routineEditorColorText: {
    color: '#FFFFFF',
    marginLeft: 12,
    fontSize: 16,
    fontWeight: '600',
  },
  routineEditorEmojiContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginVertical: 16,
  },
  routineEditorEmojiCircle: {
    padding: 12,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: '#E1E8ED',
    backgroundColor: '#FFFFFF',
  },
  routineEditorEmoji: {
    fontSize: 30,
  },
  routineEditorCheckboxContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 24,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  routineEditorCheckboxText: {
    fontSize: 16,
    color: '#2C3E50',
    fontWeight: '500',
  },
  routineEditorSaveButton: {
    backgroundColor: '#4CAF50',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routineEditorSaveButtonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 16,
  },
  routineEditorDeleteButton: {
    backgroundColor: '#E74C3C',
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
    alignItems: 'center',
  },
  routineEditorDeleteButtonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 16,
  },

  // ===== ROUTINE ACTION SCREEN STYLES =====
  routineActionContainer: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  routineActionTaskContainer: {
    height: 600,
    width: '90%',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    borderRadius: 20,
    marginVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    alignSelf: 'center',
  },
  routineActionTaskNameText: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    marginBottom: 20,
    marginTop: -100,
  },
  routineActionTaskDescriptionText: {
    fontSize: 18,
    color: '#7F8C8D',
    textAlign: 'center',
    paddingHorizontal: 24,
    lineHeight: 24,
    marginBottom: 24,
  },
  routineActionTaskDurationText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4A90E2',
    textAlign: 'center',
    marginBottom: 32,
    marginTop: 16,
  },
  routineActionDoneButton: {
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 12,
    marginTop: 24,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routineActionDoneButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 18,
  },
  routineActionAddTaskContainer: {
    height: 600,
    justifyContent: 'center',
    alignItems: 'center',
  },
  routineActionAddTaskText: {
    fontSize: 20,
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  routineActionBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    borderRadius: 12,
    marginLeft: 0,
    marginBottom: 0,
    marginTop: 8,
  },
  routineActionBackButtonText: {
    fontSize: 16,
    marginLeft: 8,
    color: '#2C3E50',
    fontWeight: '500',
  },
  routineActionReorderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    width: '100%',
  },
  routineActionOrderInput: {
    width: 50,
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 8,
    textAlign: 'center',
    fontSize: 16,
    backgroundColor: '#FFFFFF',
  },
  routineActionHeaderContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E1E8ED',
    borderRadius: 16,
    marginHorizontal: 12,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routineActionHeaderTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    flexWrap: 'wrap',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  routineActionHeaderTitleContainer: {
    alignItems: 'center',
    width: '100%',
    marginTop: 0,
  },
  routineActionTaskActionContainer: {
    position: 'absolute',
    top: 16,
    right: 16,
    flexDirection: 'row',
    gap: 12,
  },
  routineActionStepNumberContainer: {
    backgroundColor: '#4CAF50',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  routineActionStepNumberText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  routineActionMotivationText: {
    fontSize: 16,
    color: '#4CAF50',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 0,
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  routineActionRefreshMotivationButton: {
    position: 'absolute',
    top: 16,
    right: 100,
    backgroundColor: 'transparent',
    padding: 8,
  },

  // ===== ADD TASK SCREEN STYLES =====
  addTaskContainer: {
    flex: 1,
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  addTaskBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 20,
    padding: 8,
  },
  addTaskBackButtonText: {
    fontSize: 16,
    marginLeft: 8,
    color: '#4A90E2',
    fontWeight: '500',
  },
  addTaskHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 24,
    color: '#2C3E50',
  },
  addTaskInputField: {
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#2C3E50',
  },
  addTaskSaveButton: {
    backgroundColor: '#4CAF50',
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addTaskSaveButtonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 16,
  },
  addTaskPickerContainer: {
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 12,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  addTaskPicker: {
    height: 56,
    width: '100%',
  },
  addTaskLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#2C3E50',
  },
  addTaskInputContainer: {
    marginBottom: 16,
  },
  addTaskDisabledInput: {
    backgroundColor: '#F1F2F6',
    color: '#BDC3C7',
  },
  addTaskAddToEndButton: {
    backgroundColor: '#4A90E2',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  addTaskAddToEndButtonActive: {
    backgroundColor: '#7F8C8D',
  },
  addTaskAddToEndText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },

  // ===== CALENDAR SCREEN STYLES =====
  calendarContainer: {
    flexGrow: 1,
    padding: 24,
    backgroundColor: '#F8F9FA',
  },
  calendarHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 12,
    color: '#2C3E50',
  },
  calendarGoalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  calendarGoalText: {
    fontSize: 16,
    color: '#FFFFFF',
    flex: 1,
    fontWeight: '500',
  },
  calendarCompletedText: {
    textDecorationLine: 'line-through',
    color: '#BDC3C7',
  },
  calendarCounter: {
    marginRight: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 8,
    borderRadius: 8,
  },
  calendarCounterText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  calendarNoGoals: {
    alignItems: 'center',
    marginTop: 24,
  },
  calendarDeleteButton: {
    borderWidth: 2,
    borderColor: '#FFFFFF',
    borderRadius: 16,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },

  // ===== GPT PROMPTER SCREEN STYLES =====
  gptPrompterContainer: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  gptPrompterMainContent: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  gptPrompterConversationContainer: {
    flex: 1,
    padding: 24,
  },
  gptPrompterMessageBubble: {
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    maxWidth: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  gptPrompterUserBubble: {
    backgroundColor: '#4A90E2',
    alignSelf: 'flex-end',
  },
  gptPrompterGptBubble: {
    backgroundColor: '#FFFFFF',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  gptPrompterUserText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  gptPrompterGptText: {
    color: '#2C3E50',
    fontSize: 16,
  },
  gptPrompterInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 1,
    borderColor: '#E1E8ED',
    backgroundColor: '#FFFFFF',
  },
  gptPrompterInput: {
    flex: 1,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#F8F9FA',
    fontSize: 16,
    color: '#2C3E50',
    maxHeight: 100,
    borderWidth: 1,
    borderColor: '#E1E8ED',
  },
  gptPrompterSendButton: {
    marginLeft: 12,
    backgroundColor: '#4A90E2',
    borderRadius: 50,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },

  // ===== COLOR PICKER MODAL STYLES =====
  colorPickerModalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  colorPickerModalContainer: {
    width: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  colorPickerModalHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 24,
    color: '#2C3E50',
  },
  colorPickerModalPaletteContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 24,
  },
  colorPickerModalColorCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin: 8,
    borderColor: '#E1E8ED',
    borderWidth: 2,
  },
  colorPickerModalSelectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
    padding: 12,
    backgroundColor: '#E8F4FD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4A90E2',
  },
  colorPickerModalResetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
    padding: 12,
    backgroundColor: '#FFF3E0',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FF9800',
  },
  colorPickerModalCancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#FFEBEE',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E74C3C',
  },
  colorPickerModalButtonText: {
    fontSize: 16,
    marginLeft: 12,
    fontWeight: '600',
  },
});

export default universalStyles; 